apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: "infrastructure"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sos
        image: "library/sonarqube:6.7.1-alpine"
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          protocol: TCP
          name: http
        - containerPort: 9092
          protocol: TCP
          name: search