apiVersion: v1
kind: Service
metadata: 
  name: sonarqube-service
  namespace: "infrastructure"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: sonarqube
  ports:
  - port: 9000
    name: http
  - port: 9002
    name: search