---
apiVersion: v1
kind: Template
metadata:
  name: "sos-service-ephemeral"
  annotations:
    description: "Provides sos service template"
labels:
  template: "sos-service-template"

################################################################################
# Parameters
################################################################################

parameters:
  - name: "NAMESPACE"
    description: "Kubernetes namespace name"
    value: "test"
    required: true
    parameterType: "string"

objects:
- apiVersion: v1
  kind: Service
  metadata: 
    name: sos-service
    namespace: "$(NAMESPACE)"
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
  spec:
    type: LoadBalancer
    selector:
      app: sos
    ports:
    - port: 80
      name: http