---
apiVersion: v1
kind: Template
metadata:
  name: "sos-deployment-ephemeral"
  annotations:
    description: "Provides sos deployment template"
labels:
  template: "sos-deployment-template"

################################################################################
# Parameters
################################################################################

parameters:
  - name: "NAMESPACE"
    description: "Kubernetes namespace name"
    value: "test"
    required: true
    parameterType: "string"
  - name: "VERSION"
    description: "SOS image version"
    value: "latest"
    required: true
    parameterType: "string"

objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: sos-deployment
    namespace: "$(NAMESPACE)"
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: sos
      spec:
        containers:
        - name: sos
          image: "174038932576.dkr.ecr.us-east-2.amazonaws.com/demo-webapp:$(VERSION)"
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            protocol: TCP
            name: http
          env:
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: '"No"'
          volumeMounts:
          - name: sos-data
            mountPath: "/var/lib/sqlite"
        volumes:
        - name: sos-data
          emptyDir: {}